stages:
  - name: Build and Push
    steps:
      - publishImageConfig:
          dockerfilePath: ./docker/Dockerfile
          buildContext: ./
          tag: docker.dev.folio.org/platform-complete:folijet-latest
          pushRemote: true
          registry: docker.dev.folio.org
        env:
          PLUGIN_BUILD_ARGS_FROM_ENV: OKAPI_URL, TENANT_ID
        envFrom:
          - sourceName: tenant-config
            sourceKey: TENANT_ID
          - sourceName: tenant-config
            sourceKey: OKAPI_URL
        cpuLimit: 1500m
        memoryLimit: 8Gi
        cpuRequest: 100m
        memoryRequest: 100Mi
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-mf42h:folijet-helmcharts-platform-complete
          version: 0.1.7
          answers:
            image.repository: docker.dev.folio.org/platform-complete
            image.tag: folijet-latest
            ingress.enabled: true
            ingress.hosts[0].host: folijet.ci.folio.org
            ingress.hosts[0].paths[0]: /
            resources.limits.cpu: 700m
            resources.limits.memory: 786Mi
            postJob.enabled: false
          name: platform-complete
          targetNamespace: folijet
timeout: 60
branch:
  include:
    - folijet-rancher
notification: {}
