// const platformCore = require('@folio/platform-core/stripes.config.js');
// const platformERM = require('@folio/platform-erm/stripes.config.js');
// const { merge } = require('lodash');

module.exports = {
  okapi: {
    authnUrl: "https://folio-edev-spitfire-keycloak.ci.folio.org",
    uiUrl: "https://folio-edev-spitfire-diku.ci.folio.org",
    url: "https://ecs-folio-edev-spitfire-kong.ci.folio.org",
  },
  config: {
    logCategories: 'core,path,action,xhr',
    logPrefix: '--',
    maxUnpagedResourceCount: 2000,
    showPerms: false,
    preserveConsole: true,
    useSecureTokens: true,
    tenantOptions: {
      consortium: { name: 'consortium', clientId: 'consortium-application' },
      college: { name: 'college', clientId: 'college-application' },
    },
  },

  modules: {
    '@folio/acquisition-units': {},
    '@folio/agreements': {},
    '@folio/bulk-edit': {},
    '@folio/calendar' : {},
    '@folio/checkin' : {},
    '@folio/checkout' : {},
    '@folio/circulation' : {},
    '@folio/courses' : {},
    '@folio/data-import' : {},
    '@folio/developer' : {},
    '@folio/erm-comparisons' : {},
    '@folio/erm-usage': {},
    '@folio/eholdings' : {},
    '@folio/export-manager': {},
    '@folio/finance' : {},
    "@folio/gobi-settings": {},
    '@folio/handler-stripes-registry': {},
    '@folio/inventory' : {},
    '@folio/invoice': {},
    '@folio/ldp': {},
    '@folio/licenses': {},
    '@folio/lists': {},
    '@folio/local-kb-admin': {},
    '@folio/marc-authorities': {},
    '@folio/myprofile' : {},
    '@folio/notes' : {},
    '@folio/oai-pmh' : {},
    '@folio/orders': {},
    '@folio/organizations' : {},
    '@folio/plugin-bursar-export' : {},
    '@folio/plugin-create-inventory-records' : {},
    '@folio/plugin-find-agreement': {},
    '@folio/plugin-find-authority' : {},
    '@folio/plugin-find-contact': {},
    '@folio/plugin-find-eresource': {},
    '@folio/plugin-find-erm-usage-data-provider': {},
    '@folio/plugin-find-fund': {},
    '@folio/plugin-find-import-profile' : {},
    '@folio/plugin-find-instance' : {},
    '@folio/plugin-find-organization' : {},
    '@folio/plugin-find-package-title': {},
    '@folio/plugin-find-po-line': {},
    '@folio/plugin-find-user' : {},
    '@folio/plugin-query-builder' : {},
    '@folio/quick-marc': {},
    '@folio/reading-room': {},
    '@folio/receiving' : {},
    '@folio/requests' : {},
    '@folio/servicepoints' : {},
    '@folio/service-interaction': {},
    '@folio/plugin-eusage-reports': {},
    '@folio/stripes-authority-components' : {},
    '@folio/stripes-erm-components': {},
    '@folio/tags': {},
    '@folio/tenant-settings' : {},
    '@folio/users' : {},
    '@folio/serials-management' : {},
    '@folio/stripes-marc-components' : {}
  },

  branding: {
    logo: {
      src: './tenant-assets/opentown-libraries-logo.png',
      alt: 'Opentown Libraries',
    },
    favicon: {
      src: './tenant-assets/folio-favicon.png',
    },
  },
};

// module.exports = merge({}, platformCore, platformERM, platformComplete);
